//! SeaORM Entity. Generated by sea-orm-codegen 0.9.2

use sea_orm::entity::prelude::*;
use sea_orm::strum::IntoEnumIterator;
use sea_orm::Iterable;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "t_material_object")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub create_time: Option<i64>,
    pub delete_tag: Option<bool>,
    pub update_time: Option<i64>,
    pub description: Option<String>,
    pub name: Option<String>,
    pub state: Option<i32>,
    #[sea_orm(column_type = "Custom(\"array\".to_owned())", nullable)]
    pub tags: Option<String>,
    pub r#type: Option<i32>,
    pub object_local_path: Option<String>,
    pub source_obj_local_path: Option<String>,
    pub source_obj_url: Option<String>,
    pub target_obj_url: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
